replicaCount: 1
name: hobbit

image:
  name: hobbit
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  externalPort: 8080
  internalPort: 8080
  externalDebugPort: 5005
  internalDebugPort: 5005

db:
  name: mongo
  persitentVolumeClaimName: mongo-pvc
  storage: 256Mi
  externalPort: 27017
  internalPort: 27017
