openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
paths:
  /lists/children:
    get:
      tags:
        - List
      description: Return the active children list
      operationId: getChildrenList
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ChildrenGroupDTO'

  /lists/customers:
    get:
      tags:
        - List
      description: Return the active customers list
      operationId: getCustomersList
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CustomerListDTO'

  /lists/emails/{group}:
    get:
      tags:
        - List
      description: Return the active customers list emails by group
      operationId: getEmailsList
      parameters:
        - name: group
          description: the group of the customer childrens
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/GroupDTO'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmailsGroupDTO'

  /search/customer:
    get:
      tags:
        - Search
      description: Search customers by adult or child name
      operationId: searchCustomer
      parameters:
        - name: text
          description: the text to search
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CustomerListDTO'

components:
  schemas:
    ChildrenGroupDTO:
      description: List of children's basic info for a concrete group
      type: object
      properties:
        group:
          description: The children's group
          type: string
        children:
          type: array
          items:
            $ref: '#/components/schemas/ChildListDTO'

    ChildListDTO:
      description: Children's basic info
      type: object
      properties:
        code:
          type: integer
          format: int32
        shortName:
          type: string

    CustomerListDTO:
      description: Customer's basic info
      type: object
      properties:
        code:
          type: integer
          format: int32
        shortName:
          type: string
        children:
          type: array
          items:
            $ref: '#/components/schemas/ChildListDTO'

    EmailsGroupDTO:
      description: List of customers' emails for a concrete group
      type: object
      properties:
        group:
          $ref: '#/components/schemas/GroupDTO'
        emails:
          description: The customers email
          type: array
          items:
            type: string

    GroupDTO:
      description: Group where the children are
      type: string
      default: ALL
      enum:
        - ALL
        - EI_1
        - EI_2
        - EI_3
