openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
paths:
  /lists/children:
    get:
      tags:
        - List
      description: Return the active children list
      operationId: getChildrenList
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChildrenListDTO'
components:
  schemas:
    ChildrenListDTO:
      description: List of children's basic info
      type: object
      properties:
        children:
          type: array
          items:
            $ref: '#/components/schemas/ChildListDTO'
    ChildListDTO:
      description: Children's basic info
      type: object
      properties:
        shortName:
          type: string
        code:
          type: integer
          format: int32
