openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
paths:
  /lists/children:
    get:
      tags:
        - List
      description: Return the active children list
      operationId: getChildrenList
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ChildrenGroupDTO'

  /lists/customers:
    get:
      tags:
        - List
      description: Return the active customers list
      operationId: getCustomersList
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CustomerListDTO'


components:
  schemas:
    ChildrenGroupDTO:
      description: List of children's basic info for a concrete group
      type: object
      properties:
        group:
          description: The children's group
          type: string
        children:
          type: array
          items:
            $ref: '#/components/schemas/ChildListDTO'
    ChildListDTO:
      description: Children's basic info
      type: object
      properties:
        code:
          type: integer
          format: int32
        shortName:
          type: string
    CustomerListDTO:
      description: Customer's basic info
      type: object
      properties:
        code:
          type: integer
          format: int32
        shortName:
          type: string
        children:
          type: array
          items:
            $ref: '#/components/schemas/ChildListDTO'
