apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    name: {{ .Values.name }}
  {{- template "labels" . }}
spec:
  selector:
    app: {{ .Values.name }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.app.externalPort }}
      targetPort: {{ .Values.app.internalPort }}
    - name: debug
      protocol: TCP
      port: {{ .Values.app.externalDebugPort }}
      targetPort: {{ .Values.app.internalDebugPort }}
  type: LoadBalancer