apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.db.persitentVolumeClaimName }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.db.storage }}