apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.db.persitentVolumeName }}
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.db.storage }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.db.persitentVolumePath }}
