apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db.name }}
spec:
  selector:
    app: {{ .Values.db.name }}
  ports:
    - port: {{ .Values.db.externalPort }}
      targetPort: {{ .Values.db.internalPort }}