apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.dba.name }}
spec:
  selector:
    app: {{ .Values.dba.name }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.dba.externalPort }}
      targetPort: {{ .Values.dba.internalPort }}
  type: LoadBalancer