apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.dba.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.dba.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.dba.name }}
    spec:
      containers:
        - name: {{ .Values.dba.name }}
          image: {{ .Values.dba.name }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: ME_CONFIG_MONGODB_SERVER
              value: {{ .Values.db.name }}
          ports:
            - containerPort: {{ .Values.dba.internalPort }}