apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    name: {{ .Values.name }}
  {{- template "labels" . }}
spec:
  selector:
    app: {{ .Values.name }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
    - name: debug
      protocol: TCP
      port: {{ .Values.service.externalDebugPort }}
      targetPort: {{ .Values.service.internalDebugPort }}
  type: {{ .Values.service.type }}