appVersion: 5.3.0

springdoc:
  api-docs:
    path: /api-docs
#  swagger-ui:
#    disable-swagger-default-url: true
#    configUrl: "/api-docs/swagger-config"

invoices:
  maxAmount: 2500
  currency: €

api:
  base-path: /

formatting:
  spreadSheetDateFormat: "d-mmm-yy"  # https://poi.apache.org/apidocs/dev/org/apache/poi/ss/usermodel/BuiltinFormats.html
  spreadSheetCurrencyFormat: "#,##0.00_);[Red]-#,##0.00"

apiKey: "98162313-dc76-4ac9-b18c-8fd23e938085"

jasypt:
  encryptor:
    bean: stringEncryptor

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: fake_username
    password: fake_password
    properties:
      mail:
        smtp:
          auth: true
        starttls:
          enable: true
