db:
  name: hobbit_dev

springdoc:
  api-docs:
    path: /api-docs

invoices:
  maxAmount: 2500
  currency: €

api:
  base-path: /
#spring:
#  jackson:
#    serialization:
#      WRITE_DATES_AS_TIMESTAMPS: false