db:
  name: hobbit_dev

business:
  businessName: "Test businessName"
  addressLine1: "Test addressLine1"
  addressLine2: "Test addressLine2"
  addressLine3: "Test addressLine3"
  addressLine4: "Test addressLine4"
  taxIdLine: "Test taxIdLine"

  bddBusinessPrefix: TEST
  bddBusinessId: ES92000A22316012
  bddBusinessIban: ES8400817164314613054357
  bddBankBic: BSABESM1993
  bddCountry: ES
  bddPurposeCode: OTHR

  paymentTypeNotes:
    BANK_DIRECT_DEBIT: Bank direct debit payment type note
    BANK_TRANSFER: Bank transfer payment type note
    VOUCHER: Voucher payment type note
    CASH: Cash payment type note
    OTHER: Other payment type note