springdoc:
  api-docs:
    path: /api-docs

db:
  host: mongo-server
  port: 27017

invoices:
  maxAmount: 2500
  currency: €

api:
  base-path: /

business:
  businessName: "BusinessName"
  addressLine1: "AddressLine1"
  addressLine2: "AddressLine2"
  addressLine3: "AddressLine3"
  addressLine4: "AddressLine4"
  taxIdLine: "TaxIdLine"

  bddBusinessPrefix: TEST
  bddBusinessId: ES92000A22316012
  bddBusinessIban: ES8400817164314613054357
  bddBankBic: BSABESM1993
  bddCountry: ES
  bddPurposeCode: OTHR

  paymentTypeNotes:
    BANK_DIRECT_DEBIT: Bank direct debit payment type note
    BANK_TRANSFER: Bank transfer payment type note
    VOUCHER: Voucher payment type note
    CASH: Cash payment type note
    OTHER: Other payment type note
    RECTIFICATION: Rectification payment type note

formatting:
  locale: "en_US"
  longDateFormat: "MMMM d, yyyy"
  spreadSheetDateFormat: "d-mmm-yy"  # https://poi.apache.org/apidocs/dev/org/apache/poi/ss/usermodel/BuiltinFormats.html
  spreadSheetCurrencyFormat: "#,##0.00_);[Red]-#,##0.00"

apiKey: "98162313-dc76-4ac9-b18c-8fd23e938085"

jasypt:
  encryptor:
    bean: stringEncryptor

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: fake_username
    password: fake_password
    properties:
      mail:
        smtp:
          auth: true
        starttls:
          enable: true
