db:
  host: mongo_server
  port: 27017
  name: hobbit_prod

business:
  businessName: "Centre d'Educació Infantil Hobbiton, S.L."
  addressLine1: "Carrer de Bisbe Rafael Josep Verger, 4"
  addressLine2: "07010 Palma, Illes Balears"
  addressLine3: "Tel.: 971 90 99 88"
  addressLine4: "www.hobbiton.es . hobbit@hobbiton.es"
  taxIdLine: "NIF: B57398000"

  bddBusinessPrefix: HOBB
  bddBusinessId: ES92000B57398000
  bddBusinessIban: ES3721003173162200072562
  bddBankBic: CAIXESBBXXX
  bddCountry: ES
  bddPurposeCode: OTHR

  paymentTypeNotes:
    BANK_DIRECT_DEBIT: Pagament mitjançant rebut domiciliat en compte corrent
    BANK_TRANSFER: Pagament mitjançant transferència al compte corrent ES3721003173162200072562
    VOUCHER: Pagament mitjançant xec escoleta
    CASH: Pagament al comptat
    OTHER:
    RECTIFICATION:

formatting:
  locale: "ca_ES"
  longDateFormat: "d MMMM yyyy"